### PR TITLE
Update Project to support Swift 2.3

### LINKED ISSUE #54: Add support for Swift 2.3
Looks like we could cut a branch from 0f23a8 to make a 2.3 compatible version.

### PR DESCRIPTION
**Pull request by regnerjr**
Fixes #54 

No code changes required. Just update the project files and bumped the pod spec to a new version.

Let me know if you need any more help or support. 
Thanks for making this awesome project. 

(I'm not sure how cocoa pods versions work, if this needs a release or what) Thanks again!

### CODE REVIEW

**Comment by regnerjr** [comment]
I guess I don't really want to merge this into master.... maybe there should just be a Swift2.3 branch as a stepping stone. Thanks again for you help.

**Comment by dreese** [comment]
I think this would be great as its own branch with a pod release (with `v0.1.7`) that is just for Swift 2.3 support. Then `0.2.0` can be Swift 3+.

**Comment by bellots** [comment]
updates for this branch?

**Comment by teodorpatras** [comment]
This basically makes the whole library to use Swift 2.3. Please make the PR to the `origin/swift2.3` branch.

**Comment by dreese** [comment]
@regnerjr Will you have any trouble creating another PR from `regnerjr:swift2.3` into `origin/swift2.3`?

**Pull request closed without merging**
