### PR TITLE
Added will reveal/hide delegate methods

### PR DESCRIPTION
**Pull request by Oleygen**

### CODE REVIEW

**Comment by teodorpatras** [comment]
Thanks for your contribution! There's one thing though: what if the user pans the center panel to open the side menu? Then the willReveal is not called before revealing the side menu.

**Comment by Oleygen** [comment]
Yes you right. 
Looks like we need to call willReveal (for pan feature) when 
1) Side panel is fully hidden
2) Pan gesture did began (no matter do we really want to open side panel)
The main purpose of willReveal is to perform pre-installation of tableView which contains side panel content

As for willHide we should to apply symmetric logic.
If you ok with this - I will perform necessary changes and pull request agains\

**Comment by teodorpatras** [comment]
Actually there is a method: `prepare(sidePanelForDisplay:Bool)` you can move the willReveal/Hide calls there. It should be enough.

**Comment by Oleygen** [comment]
If we use your approach the willHide method will be called after side panel did hide actually. Are we ok with this?

**Comment by teodorpatras** [comment]
You're right.. let's roll back to the previous idea: just put the willReveal notification in the `case .began && !sidePanelVisible`

**Comment by piv199** [comment]
@teodorpatras hi I missed this pr, and created a new one, I will take a look tomorrow...

#69

**Pull request closed without merging**
