### PR TITLE
modal orientation change fix

### PR DESCRIPTION
**Pull request by bonebox**
Resize the SideMenuController views properly when returning from a controller presented modally in which an orientation change occurred.

### CODE REVIEW

**Comment by bonebox** [comment]
Currently if you display a modal view from a view controller managed by SideMenuController, change device orientation while the modal is active (i.e., from portrait to landscape) then dismiss the modal, SideMenuController does not update its views properly (retains dimensions from before the modal presentation).  This fixes that.

**Comment by iAppDeveloper88** [comment]
Works well, but if the content view controller is a UICollectionView it breaks layout constraints on rotation

**Comment by trungnguyen1791** [comment]
Did you guys have any update related to this issue? @iAppDeveloper88 @bonebox

**Comment by teodorpatras** [comment]
this project is unfortunately not actively maintained, feel free to fork it

**Pull request closed without merging**
